### PR TITLE
feat: add list.sortFunc

### PR DESCRIPTION
**Pull request by liz3**
# feat: list.sortFunc

### What's Changed:
Adds a function to list implemented in dictu which uses quickSort to allow custom sorting which is suuuper useful for a lot of problems. I would have preferred to implement this is C too but there doesn't seam to be a straight forward way to pass callbacks into c. Using a hybrid approach would have been hacky too, but of course this approach does duplicate the sorting logic.

### Type of Change:

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping:

- [x] Tests have been updated to reflect the changes done within this PR (if applicable).
- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

### CODE REVIEW

**Comment by briandowns** [comment]
LGTM

**Review by Jason2605 — COMMENTED** [review]
Yeah unfortunately due to some optimisations in the VMs main loop it means it's no reentrant so using C wouldn't be possible in it's current state, just one little comment!

**Comment by liz3** [comment]
> Yeah unfortunately due to some optimisations in the VMs main loop it means it's no reentrant so using C wouldn't be possible in it's current state, just one little comment!

Is there something you wan't me to change in the PR, referencing: `just one little comment!`

**Comment by Jason2605** [comment]
Oh what I typed out a comment 😢 it was just a note in the documentation explaining the return value of the callback and how it works essentially

**Comment by liz3** [comment]
@Jason2605 done!

**Comment by Jason2605** [comment]
Legend, thank you for this!

**Pull request merged**
