### PR TITLE
fix: add reallocate and memory macros to ffi

### PR DESCRIPTION
**Pull request by liz3**
#  Add reallocate and memory macros to ffi

### What's Changed:
I added `reallocate` to the FFI as a function and updated the ffi header for it to have the memory macros available.

### Type of Change:

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping:

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).
- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

### CODE REVIEW

**Comment by Jason2605** [comment]
Apologies for being slow, I'm currently in a different country! I will get around to this, thank you

**Comment by liz3** [comment]
Thanks, i have been writing a few "addons"? and was in need of those macros.
* https://github.com/liz3/dictu-pq
* https://github.com/liz3/dictu-mongo
* https://github.com/liz3/dictu-ui

**Comment by Jason2605** [comment]
Woah these look really cool! It seems as though the tests are failing on OS X mind, we probably need to look into that

**Comment by liz3** [comment]
> Woah these look really cool! It seems as though the tests are failing on OS X mind, we probably need to look into that

Seams to be fixed, the issue was that the MacOS runner apparently started using arm64 and the shared object for the test was x64, this might be a idea to add a constant to System, like Node.js's `process.arch` in order to check that.

But in terms of this patch it seams to work!

**Comment by Jason2605** [comment]
AHhh good find, thank you for this, much appreciated!

**Pull request merged**
