### PR TITLE
Win32 fixes

### PR DESCRIPTION
**Pull request by jamsilva**
### Well detailed description of the change :

Corrected some errors in compilation for Win32. Ability to compile Win32 version on Linux using MinGW.
Modified linenoise with support for Win32 and additional features not available in the currently included linenoise (Such as Ctrl-R history search).

#

### Type of change:

- [x] Bug fix
- [x] New feature

### CODE REVIEW

**Comment by Jason2605** [comment]
Thanks for this! I have a pretty busy week this week but will try my best to get round to them at the weekend, sorry!

**Comment by Jason2605** [comment]
Just as a quick check, did you replace the linenoise files completely? Just as the linenoise file within Dictu does have a couple of custom additions to it

**Comment by jamsilva** [comment]
Yes, I replaced it with a different fork. I did not notice any problems at compile-time but if you can tell me what custom additions you made, I can look into it.

**Comment by Jason2605** [comment]
Actually sorry ignore me I'm talking rubbish, this looks great thank you very much!

**Pull request merged**
