### PR TITLE
Added test run in Docker build

### PR DESCRIPTION
**Pull request by avinashupadhya99**
Tests are run before the Docker image build is completed.

### CODE REVIEW

**Comment by Jason2605** [comment]
Something i missed on the last PR as well actually, if we're installing libcurl, then we have all we need to enable the HTTP lib, so we can remove that flag when building

**Comment by avinashupadhya99** [comment]
There were errors while building with HTTP

```
c/optionals/http.c: In function 'get':
c/optionals/http.c:192:9: error: call to '_curl_easy_setopt_err_write_callback' declared with attribute warning: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror=attribute-warning]
  192 |         curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeResponse);
      |         ^
c/optionals/http.c: In function 'post':
c/optionals/http.c:280:9: error: call to '_curl_easy_setopt_err_write_callback' declared with attribute warning: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror=attribute-warning]
  280 |         curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeResponse);
      |         ^
c/optionals/http.c:280:9: error: call to '_curl_easy_setopt_err_write_callback' declared with attribute warning: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror=attribute-warning]
lto1: all warnings being treated as errors
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: Leaving directory '/Dictu'
make[1]: *** [c.make:45: build/dictu] Error 1
make: *** [Makefile:15: dictu] Error 2
```

**Comment by Jason2605** [comment]
Ah i see, but thats fine now because that was an issue resolved in #309 so we should be able to remove that flag now

**Comment by Jason2605** [comment]
Perfect, thank you very much!

**Pull request merged**
