### PR TITLE
added an example called the staircase

### PR DESCRIPTION
**Pull request by Pey-crypto**
Staircase example

### CODE REVIEW

**Comment by Jason2605** [comment]
Unfortunately this code snippet won't run. The `++` and `--` operators are only in Dictu in a prefix format, not postfix. After fixing these errors i'm not entirely sure what the output was supposed to give me either.

**Comment by Pey-crypto** [comment]
The program is supposed to generate a staircase
Given an input of 4 
      #
    ##
  ###
####
it would generate the above figure

**Comment by Jason2605** [comment]
Unfortunately when you run the program that is not the outcome, the following is:

```
Enter a number:5
' '
' '
' '
' '
'1'
'
'
' '
' '
' '
'1'
'1'
'
'
' '
' '
'1'
'1'
'1'
'
'
' '
'1'
'1'
'1'
'1'
'
'
'1'
'1'
'1'
'1'
'1'
'
'
```

**Comment by Pey-crypto** [comment]
Let me see if I can fix that

**Comment by Jason2605** [comment]
Any update @Pey-crypto?

**Comment by Pey-crypto** [comment]
yeah, I need to include another print method, like printf in c. Working on it

**Comment by Jason2605** [comment]
I'm going to close this out due to inactivity. Feel free to re-open this if you're still working on it!

**Pull request closed without merging**
