### PR TITLE
remove unneeded file

### PR DESCRIPTION
**Pull request by briandowns**
### What's Changed:

Removes an unneeded file from the root of the repository.

### Type of Change:

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping:

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).
- [ ] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by Jason2605** [comment]
We really need to look at that test, it seems to be failing on each run

**Comment by briandowns** [comment]
Really strange how it's fine in one test and then consistently blows up in others, after having been fine for awhile.

**Comment by Jason2605** [comment]
Hmmm looks as though this extended sleep is running forever on mac. Potentially work marking it as skipped for now and we can try look into it

**Comment by briandowns** [comment]
yeah, that was a initial test and then my flight's WiFi went out so I had to wait a bit. I'll skip for now while I keep digging.

**Comment by Jason2605** [comment]
Ah no worries at all mate! Thanks for the cleanup

**Pull request merged**
