### PR TITLE
Fixed self import Segmentation fault

### PR DESCRIPTION
**Pull request by manoharkakumani**
### Well detailed description of the change :

   While Importing the same file as a module in the same file we are getting a Segmentation fault.
Ex: if we execute the below code by writing it in test.du file
`import "./test.du";
var x = 1;
print(x);`

Resolves: #

  After creating the module we need to add it to vm->modules table to keep it tracked.
#

### Type of change:

 added below line in vm.c file in IMPORT opcode block
`tableSet(vm, &vm->modules, fileName, OBJ_VAL(module));`

- [ ] Bug fix

- [ ] New feature

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).

- [ ] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### Preview (Screenshots) :

Before changes

image

After Change

image

### CODE REVIEW

**Comment by Jason2605** [comment]
This is a good spot, thank you! The fix however, we will want to be slightly different. Rather than saving the filename, we should instead check for the path as this is what is being saved in newModule.

**Comment by manoharkakumani** [comment]
Have you fixed the issue? If yes I'll close the pr.
Can you please let me know where you are setting the vm->modules.

**Comment by Jason2605** [comment]
I haven't committed anything, but the above code would resolve the issue yeah. The module gets added in the call to `newModule`, the issue was we were checking for the filename given by the user, not the fully resolved file name! So good spot on your part

See here: https://github.com/dictu-lang/Dictu/blob/develop/src/vm/object.c#L45

**Comment by Jason2605** [comment]
I've now pushed the above changes to your PR, and I'll merge it in now. This means if you're participating in hacktoberfest or similar you can still get the credit 🎉

**Pull request merged**
