### PR TITLE
Add negate method to number type

### PR DESCRIPTION
**Pull request by briandowns**
Add negate method to number type

Resolves: #

### What's Changed:

Adds a new method, `negate`, to the number type.

### Type of Change:

- [ ] Bug fix
- [X] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping:

- [X] Tests have been updated to reflect the changes done within this PR (if applicable).
- [X] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by Jason2605** [comment]
Hmm interesting, we can use `-` as a prefix operator rather than a function call for negating a number - do you think we need this as a method?

```
const x = 100;
print(-x); // - 100
```

**Comment by briandowns** [comment]
Probably unnecessary then. I'll defer to you if you want it in the language. I'm happy to close the PR if you don't. 😀

**Comment by Jason2605** [comment]
Appreciate the PR but I think we probably don’t need it

**Comment by briandowns** [comment]
Cool, cool. Closing.

**Pull request closed without merging**
