### PR TITLE
feature/Hexadecimal and Exponents numbers

### PR DESCRIPTION
**Pull request by manoharkakumani**
Now language supports hex values and  exponents 
ex:
0xA2F , 0XA2F , 0xa2f , 0Xa2f
1e3,1e+5,1e-5,etc
image

### CODE REVIEW

**Comment by Jason2605** [comment]
Some good points by @NightShade256 worth following up on.

**Comment by manoharkakumani** [comment]
@NightShade256  i made changes as you suggested

**Comment by Jason2605** [comment]
@manoharkakumani The code formatting is still a bit off unfortunately. I should be able to give this a good test later on and let you know of anything i find.

**Comment by Jason2605** [comment]
I've updated your pull request to fix the formatting and add some tests for the new numeric literals.

**Pull request merged**
