### PR TITLE
Release 0.29.0

### PR DESCRIPTION
**Pull request by Jason2605**
# Release 0.29.0
## Change Log
**These are all the changes since 0.28.0**
- Internal update to how attributes are handled #635 
- Unload C module #638 
- Ensure all tests are ran #639 
- Add less than and greater than comparison operators for string types #640 
- Order docs alphabetically #643 
- Add new `UnitTest.mock()` #644 
- Add new Stack module #645 
- Range of changes to the Argparse module #648 
- Fix a memory issue with annotations #651 
- Add new Result.matchError #652 
- Add annotation inheritance #654 
- Add new List.unique() #655 
- Ability to convert a class to dict #656 
- Fix type issue with `fgetc` #657 
- Fixes an internal issue with the Table type by reverting the open addressing scheme #660 
- Ability for Abstract types to keep track of Values (ability to grey Values) #661 
- Add HTTP.put() #663 
- Add the ability to set the timeout for SQLite #668 
- Add new Enum.values() #672 
- Add HTTP.head() #673 
- Add string type to List.sort() #676 
- Add new IO module #680 
- Ability to parse hex values #684 
- Add new Net module #686 
- Allow annotations to have list / dict types #687 
- Docs fixes #688

### CODE REVIEW

**Comment by briandowns** [comment]
LGTM. Best version of Dictu yet.

**Comment by Jason2605** [comment]
Oops I got the branches the wrong way round 😂

**Comment by briandowns** [comment]
I didn't even notice. Did we want to try to get the copy file PR in? No rush. Just curious.

**Comment by Jason2605** [comment]
Yep good point, I keep forgetting about that PR

**Pull request closed without merging**
