### PR TITLE
Add net module, tests, and docs

### PR DESCRIPTION
**Pull request by briandowns**
# Add net module, tests, and docs

### What's Changed:

Adds a new module called "Net" with a couple constants, and functions.

I was imagining the next iteration of this to be to move the Socket module into this module, in some capacity.

#

### Type of Change:

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping:

- [x] Tests have been updated to reflect the changes done within this PR (if applicable).
- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by Jason2605** [comment]
Yeah moving Socket into a more generic Net module probably makes more sense. Either that or you make separate ones for each (like Python does: https://docs.python.org/3/library/ipaddress.html / https://docs.python.org/3/library/socket.html)

**Comment by briandowns** [comment]
I'll defer to your judgement on how you want to move forward. Adding Socket to Net had me start thinking about sub modules within a module and how that'd work from an implementation perspective and how it'd look from a language perspective. For the latter, I like any of the following but possibly the "/" most.

```cs
import Net:Socket
```

```cs
import Net/Socket
```

**Comment by Jason2605** [comment]
Yeah submodules will be an interesting one, we can kind of do it at the moment with `from` (although only 1 layer deep).

The only other alternative we could potentially have is:

```
import Net.Socket;
```

Def worth a think on the best syntax for them

**Review by Jason2605 — COMMENTED** [review]
Couple of little ones

**Comment by Jason2605** [comment]
Thanks for this!

I was thinking as well, I probably should have done it a while ago but I can send you an invite to the org if you'd like? You've done more than enough on the repo now to warrant it! Thank you very much!

**Comment by briandowns** [comment]
> Thanks for this!
> 
> I was thinking as well, I probably should have done it a while ago but I can send you an invite to the org if you'd like? You've done more than enough on the repo now to warrant it! Thank you very much!

Whatever works for you, works for me. :) Thanks!

**Pull request merged**
