### PR TITLE
Add support for `_` as a delimiter in numbers.

### PR DESCRIPTION
**Pull request by NightShade256**
Implements the feature as in #271 .

Added relevant tests, and checked for leaks and such.
Note: The underscore can only occur in the non fractional part of a number, this was an intentional choice. If you want me to modify it so that it can appear even in the fractional part I will happily implement that.

### CODE REVIEW

**Comment by Jason2605** [comment]
Appreciate the pull request! I'm not sure there would be many cases where the separator would be used after the decimal point however i personally think we should be consistent in allowing it on both sides not to have changing behaviour.

Something to note as well (not sure it's an "issue")
```
var x = 1_____________0;
```
Would be valid, should we consider a separator to only be a single underscore? Not sure if the extra complexity to track this would be worth the effort.

**Comment by NightShade256** [comment]
For the underscore to be allowed in fractional part, consistency would indeed be nice.

For the spammy underscore issue, I think we should let it pass since other languages like Rust also allow similar behaviour.

**Comment by NightShade256** [comment]
Simple fix, all done.

**Comment by Jason2605** [comment]
Perfect, thank you once again!

**Pull request merged**
