### PR TITLE
Dirty checkTests script to ensure all test directories are imported

### PR DESCRIPTION
**Pull request by Jason2605**
### Well detailed description of the change :

Script added to github actions to ensure tests are added to `runTests.du`.

### CODE REVIEW

**Review by briandowns — APPROVED** [review]
LGTM! 

My bad on missing that term mod import.

**Comment by Jason2605** [comment]
It's all good I've done it many a time. They are failing now though as `isatty` is false in the CI environment

**Comment by briandowns** [comment]
Hmmm. Is there any way to detect if it's under test and skip that one?

**Comment by Jason2605** [comment]
I've added a quick `ci` argument being passed when running the tests, that should be enough to sort it to be honest

**Comment by Jason2605** [comment]
There we go 🥳

**Pull request merged**
