### PR TITLE
Add UUID Module

### PR DESCRIPTION
**Pull request by briandowns**
### Well detailed description of the change :

Added a UUID module that basically wraps the common C UUID library.

Not really sure where to put the uuid library dependency. Also, I might need to make this *NIX only.

Resolves: #

#

### Type of change:

- [ ] Bug fix

- [x] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [x] Tests have been updated to reflect the changes done within this PR (if applicable).

- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by Jason2605** [comment]
It'll be failing on ubuntu as libuuid hasn't been linked to it in the CMake file, I think it'll be good to have this behind a flag too incase we ever want to compile without linking libuuid

An example with cURL:
https://github.com/dictu-lang/Dictu/blob/develop/src/CMakeLists.txt#L15-L21

**Comment by Jason2605** [comment]
Sorry, super slow on these recently! I assume none of the methods in the UUID library are available on windows systems?

**Comment by briandowns** [comment]
No. Sadly.

**Comment by Jason2605** [comment]
Thanks for this!

**Pull request merged**
