### PR TITLE
add Env.clearAll function

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <brian.downs@gmail.com>

### Well detailed description of the change :

Adds a function that clears all environment variables.

Resolves: #

#

### Type of change:

- [ ] Bug fix

- [x] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).

- [ ] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by briandowns** [comment]
I initially added it but couldn't get CI to pass. I don't have access to a Windows box to test. Frustration lead to *nix only.. :/ Added support back in.

**Comment by Jason2605** [comment]
> I initially added it but couldn't get CI to pass. I don't have access to a Windows box to test. Frustration lead to *nix only.. :/ Added support back in.

Ahh okay no worries. I'll be able to test it out on windows and try get it working

**Comment by Jason2605** [comment]
This is an interesting one. Seems whenever I unset all env vars on windows the process just exits when running the tests. In the REPL it runs the first time then exits the second (with some changes to use strchr rather that strstr).

It's causing some headaches for me on windows so I'm unsure how I feel about this one :/

**Comment by briandowns** [comment]
Happy to adjust this to be nix* only.

**Comment by Jason2605** [comment]
I think for now we can do that, will aim to revisit the windows implementation at some point

**Review by Jason2605 — APPROVED** [review]

**Comment by Jason2605** [comment]
Cheers for this 🎉

**Pull request merged**
