### PR TITLE
Release 0.27.0

### PR DESCRIPTION
**Pull request by Jason2605**
# Release 0.27.0
## Change Log
**These are all the changes since 0.26.0**
- Update HTTP timeout #558 
- Add support for shebang in scripts #560 
- Resolve an issue with the argparse module #565 
- Set follow redirects on by default and add method to httpClient #566 
- Update some stdlib modules to latest conventions #571 
- Add a new Argparse module to the stdlib #574 
- Add UUID module to stdlib #577 
- Add some new Datetime constants #579 
- Add new `System.copyFile` method #580 
- Updated STATUS_OK const name #583 
- Add in method annotations #585 
- Update documentation to include more context (e.g return types) #586 
- Add `list.splice()` method #591 
- Add some new Socket constants #595 
- Ability to deal with files in binary mode #596 
- Win32 fixes + linenoise support on windows #597 #598 #599 
- Add optional buffersize to `file.readline` #600 
- Build docker images on release #602

### CODE REVIEW

**Comment by Jason2605** [comment]
Chunky release, thank you @jamsilva and @briandowns !

**Comment by briandowns** [comment]
LGTM!

**Comment by briandowns** [comment]
Do we want to get #602 in there for this release?

**Comment by Jason2605** [comment]
I was thinking about that, will need to see if I can find some dockerhub credentials

**Comment by Jason2605** [comment]
Right added those in now, lets see how this all goes 😄

**Comment by Jason2605** [comment]
Did seem to fail unfortunately https://github.com/dictu-lang/Dictu/actions/runs/4212885678/jobs/7312224484

**Pull request merged**
