### PR TITLE
Update readme to include FreeBSD

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <brian.downs@gmail.com>

### Well detailed description of the change :

Resolves: #506 

#

### Type of change:

This is a documentation update rather than a bug fix as the original issue indicates however related nonetheless.

- [ ] Bug fix

- [ ] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).

- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by briandowns** [comment]
Looks like some 502 http errors on a mac run. Unable to rerun the job.

**Comment by Jason2605** [comment]
Sorry for the slow response on this one @briandowns was briefly in another country! Should be all sorted now, thank you for the PR and getting it working on FreeBSD. I wonder if we can also extend this to run the tests in actions on FreeBSD, but that can come later!

**Comment by briandowns** [comment]
No worries at all. I hope my latest comment wasn't taken as some sort of "ping". As for tests, I was gonna work on that this weekend. :D

**Comment by Jason2605** [comment]
Not at all, I'm glad you did it, it served as a reminder for myself! Thank you very much, that sounds great.

**Pull request merged**
