### PR TITLE
Support variadic functions/methods

### PR DESCRIPTION
**Pull request by ziord**
### Well detailed description of the change :

This change adds support for variadic functions/methods. The caveats are:
- not supported in class constructors
- not supported in function/methods with default/optional parameters

Resolves: #521
#

### Type of change:

- [x] New feature

#

### Housekeeping

- [x] Tests have been updated to reflect the changes done within this PR (if applicable).

- [x] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### CODE REVIEW

**Comment by Jason2605** [comment]
First of all, thank you @ziord for this PR!

This all looks great, we will just need to get some documentation written up before merging in. I don't mind helping with this though!

**Comment by ziord** [comment]
Thanks, @Jason2605! I just wanted to ensure the code changes were acceptable before making documentation. If I get stuck on it, I'll reach out to you 😄

**Comment by Jason2605** [comment]
Thank you very much for this @ziord!

**Comment by Jason2605** [comment]
Thank you very much for this @ziord!

**Pull request merged**
