### PR TITLE
add additional math mod values

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <bdowns@Brians-MacBook-Pro.local>

### Well detailed description of the change :

Add additional native properties in math mod.

Resolves: 
 
#

### Type of change:

- [ ] Bug fix

- [x] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).

- [ ] Documentation has been updated to reflect the changes done within this PR (if applicable).

### CODE REVIEW

**Comment by Jason2605** [comment]
Hi there @briandowns!

Firstly thanks for the PR! Unfortunately this has broken the tests, would be good to extend the maths tests to include the new values you've added as well

**Comment by briandowns** [comment]
Ugh, my fault. Updates pushed and I'll monitor to make sure CI passes. Thank you!

**Comment by Jason2605** [comment]
One more test is using `Math.pi`!

Interesting point here though is that we are using the `double` type to represent all values within Dictu. This means numeric values will only have precision for ~15 decimal places, anything after that is lost (silently).

**Comment by briandowns** [comment]
That makes sense. I was pulling this from an extremely modified fork. I'll update.

**Comment by briandowns** [comment]
Thanks for the help on this @Jason2605 . I have a few more PRs to add for some more features if that's ok.

**Comment by Jason2605** [comment]
No worries! Yeah I'm all for extra contributions, feel free!

Last thing we need to do here is to just add these new values to the docs, I probably should have said previously!

See here: https://github.com/dictu-lang/Dictu/blob/develop/docs/docs/standard-lib/math.md#constants

**Comment by briandowns** [comment]
All set!

**Comment by Jason2605** [comment]
Thank you for the PR!

**Pull request merged**
